# Generated by Django 4.2.4 on 2023-09-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListaReproduccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
